### ISSUE TITLE
installing xergm using R version 4.0

### ISSUE THREAD

**Issue by jmp243** [leifeld/xergm#6]
I am having trouble installing xergm on RStudio. Using RSwitch, I tried reverting to an older version of R (trying versions 3.3.3 and 3.6.3) and the install still did not work. I assume there is a problem with CRAN.

     install.packages("xergm")
     Warning in install.packages :
     package ‘xergm’ is not available (for R version 4.0.0)

**Comment by leifeld** [comment]
Hi there. `xergm` is a meta-package that merely depends on `btergm`, `tnam`, `GERGM`, `rem`, and `xergm.common`. As `GERGM` and `tnam` were removed from CRAN due to some new CRAN policies that the package maintainers haven't fully addressed, it is impossible for me to upload `xergm` to CRAN at the moment as all dependencies must be installable. The same thing applies when you try to install `xergm` from GitHub. So I'd recommend installing the respective package you are interested in directly, for example `btergm` for TERGMs (e.g., from CRAN) or `GERGM` for GERGMs (in this case from GitHub because not available from CRAN). Hope this helps.
